# Cloud Run deployment configuration
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: self-order-agent
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # CPU and memory allocation
        run.googleapis.com/cpu: "1"
        run.googleapis.com/memory: "512Mi"
        # Maximum number of requests per instance
        run.googleapis.com/max-scale: "10"
        run.googleapis.com/min-scale: "0"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/self-order-agent:latest
        ports:
        - containerPort: 8080
        env:
        # Environment variables for your agent
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/secrets/service-account-key.json
        - name: PYTHONPATH
          value: /app
        - name: PYTHONUNBUFFERED
          value: "1"
        # BigQuery and other GCP services will use default credentials
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
        # Health check
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
  traffic:
  - percent: 100
    latestRevision: true
